name = "vanilla"
mc_version = "1.20.4"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
preset_flags = "aikars"

[options]
upload_to_mclogs = false
